# Database configuration
# para visualizar o console do h2 entre na url
## localhost:8080/h2-console

spring:
  datasource:
    url: jdbc:h2:mem:appfinancas
    username: admin
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true