# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:appfinancas
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true